version: '3'
services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    #ports:
      #- 16379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset 
      POSTGRES_USER: superset 
    ports:
      - 127.0.0.1:15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      #- /hdd3/docker-volumes/superset_postgres/:/var/lib/postgresql/data

  superset:
    #user: root:root
    build:
      context: ../../
      dockerfile: contrib/docker/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # If using production, comment development volume below
      SUPERSET_ENV: production
      #SUPERSET_ENV: development
    ports:
      #- 10.8.0.1:18088:8088
      - 18088:8088
    depends_on:
      - postgres
      - redis
    volumes:
      # this is needed to communicate with the postgres and redis services
      - ./superset_config.py:/home/superset/superset/superset_config.py
      #- ./server.crt:/home/superset/server.crt
      #- ./server.key:/home/superset/server.key
      # this is needed for development, remove with SUPERSET_ENV=production
      - ../../superset:/home/superset/superset

volumes:
  postgres:
    external: false
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/hdd3/docker-volumes/superset_postgres/'
  redis:
    external: false
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/hdd3/docker-volumes/superset_redis/'

